routes/web.php
<?php

declare(strict_types=1);

use App\Enums\Role;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PasswordResetLinkController;
use App\Livewire\UserForm;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static fn () => view('application.create'));
Route::get('/bulletin-adhesion-pdf', static fn () => redirect('/BulletinAdhesion.pdf'));
Route::get('/success', static fn () => view('application.success'))->name('success');

Route::get('/archives', static fn () => view('application.archives'))
    ->name('archives')
    ->middleware(['auth', 'role:'.Role::BOARD->value]);

Route::prefix('admin')
    ->middleware(['auth', 'role:'.Role::ADMIN->value, config('jetstream.auth_session'), 'verified'])
    ->group(static function (): void {
        Route::get('', static fn () => view('admin.index', ['ref' => base_path().'/.git/refs/heads/main']))->name('admin.index');

        Route::prefix('logs')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewLogs'])->name('admin.logs');
            Route::get('clear', [AdminController::class, 'clearLogs'])->name('admin.logs.clear');
        });

        Route::prefix('users')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewUsers'])->name(AdminController::ROUTE_NAMES['users']['index']);
            Route::get('/edit/{user}', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['edit']);
            Route::get('/create', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['create']);
        });

//        Route::get('/settings', SettingsForm::class)->name('admin.settings');
    });

Route::prefix('dashboard')
    ->middleware(['auth', 'role:'.Role::BOARD->value, config('jetstream.auth_session'), 'verified'])
    ->group(function (): void {
        Route::get('', \App\Livewire\Dashboard\Dashboard::class)
            ->name('dashboard.index')
            ->middleware(['auth', 'role:'.Role::BOARD->value]);

        Route::prefix('application')->group(function (): void {
            Route::get(
                'complete/{application}',
                \App\Livewire\ApplicationComplete::class
            )->name('dashboard.application.complete')
                ->middleware(['auth', 'role:'.Role::TREASURY->value]);
        });
});

if (Features::enabled(Features::resetPasswords())) {
    // Overwrite the forgot-password post route to add enumeration protections
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
        ->middleware(['guest:'.config('fortify.guard')])
        ->name('password.email');
}

app/Models/Application.php
<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\ApplicationStatus;
use App\Enums\ContributionWay;
use App\Events\ApplicationCompletedByTreasury;
use App\Events\MemberReady;
use App\Events\NewApplication;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Gate;
use Ramsey\Uuid\Uuid;

/**
 * @property string            $id
 * @property string            $name
 * @property string            $firstname
 * @property string            $address
 * @property string            $postcode
 * @property string            $city
 * @property string            $email
 * @property string            $mobile
 * @property ?string           $company_name
 * @property ?string           $company_siret
 * @property ?string           $company_legal_address
 * @property ?string           $company_work_address
 * @property ?int              $birth_year
 * @property ?string           $gender
 * @property float             $contribution
 * @property ContributionWay   $contribution_way
 * @property bool              $mail_local
 * @property ApplicationStatus $status
 * @property Carbon            $created_at
 * @property Carbon            $updated_at
 * @property ?string           $applicant_comment
 * @property ?string           $sepa_full_name
 * @property ?string           $sepa_address
 * @property ?string           $sepa_postcode
 * @property ?string           $sepa_city
 * @property ?string           $sepa_country
 * @property ?string           $iban
 * @property ?string           $bic
 * @property ?string           $made_at
 * @property ?string           $signature
 * @property ?string           $RUM
 * @property ?string           $first_withdrawal_date
 */
class Application extends Model
{
    use HasFactory;
    use HasUuids;

    public $fillable = [
        'name',
        'firstname',
        'address',
        'postcode',
        'city',
        'email',
        'mobile',
        'company_name',
        'company_siret',
        'company_legal_address',
        'company_work_address',
        'birth_year',
        'gender',
        'contribution',
        'sepa_full_name',
        'sepa_address',
        'sepa_postcode',
        'sepa_city',
        'sepa_country',
        'iban',
        'bic',
        'made_at',
        'signature',
        'applicant_comment',
        'rum',
        'first_withdrawal_date',
    ];

    protected $casts = [
        'contribution_way' => ContributionWay::class,
        'status' => ApplicationStatus::class,
    ];

    /**
     * The model's default values for attributes.
     *
     * @var array<string, mixed>
     */
    protected $attributes = [
        'status' => ApplicationStatus::NEW,
        'mail_local' => false,
        'contribution' => 1,
        'contribution_way' => ContributionWay::SEPA,
    ];

    public static function boot(): void
    {
        parent::boot();

        self::creating(static function (self $application): void {
            if ($application->contribution_way !== ContributionWay::SEPA) {
                $application->removeSepaData();
            }
        });

        self::saving(static function (self $application): void {
            Gate::authorize($application->status->ability(), $application);
        });

        self::saved(static function (self $application): void {
            match ($application->status) {
                ApplicationStatus::NEW => NewApplication::dispatch($application),
                ApplicationStatus::COMPLETED => ApplicationCompletedByTreasury::dispatch($application),
                ApplicationStatus::READY => MemberReady::dispatch($application),
                ApplicationStatus::WELCOMED, ApplicationStatus::REJECTED, ApplicationStatus::VALIDATED => null,
            };
        });
    }

    public function newUniqueId(): string
    {
        return (string) Uuid::uuid4();
    }

    public function getShortenedId(): string
    {
        return substr($this->id, 0, 8);
    }

    public function getTitle(): string
    {
        return sprintf('%s %s. (%s)', $this->firstname, $this->name[0], $this->getShortenedId());
    }

    public function removeSepaData(): void
    {
        $this->sepa_full_name = null;
        $this->sepa_address = null;
        $this->sepa_postcode = null;
        $this->sepa_city = null;
        $this->sepa_country = null;
        $this->iban = null;
        $this->bic = null;
        $this->made_at = null;
        $this->signature = null;
    }
}

app/Livewire/ApplicationForm.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Enums\ContributionWay;
use App\Models\Application;
use App\Rules\Iban;
use App\Services\SireneAPI;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rules\Enum;
use Livewire\Attributes\On;
use SolidairesInformatique\AccessTokenException;
use SolidairesInformatique\BadParameter;
use SolidairesInformatique\CurlException;
use Spatie\Honeypot\Http\Livewire\Concerns\HoneypotData;
use Spatie\Honeypot\Http\Livewire\Concerns\UsesSpamProtection;

class ApplicationForm extends RateLimitedComponent
{
    use ConvertEmptyStringsToNull;
    use HasTextFields;
    use UsesSpamProtection;

    public Application $application;
    public bool $employee = true;
    public bool $minimalContribution = false;
    public string $wage = '';
    public float $contributionPercentage = 0.5;
    public bool $terms = false;
    public int $step = 1;
    public bool $noSiret = false;
    private SireneAPI $sireneAPI;
    public HoneypotData $extraFields;

    private const SIRET_FIELD = 'application.company_siret';
    public const REQUIRED_IF_SEPA = 'required_if:application.contribution_way,'.ContributionWay::SEPA->value;

    public function boot(SireneAPI $sireneAPI): void
    {
        $this->sireneAPI = $sireneAPI;
    }

    public function mount(): void
    {
        $this->extraFields = new HoneypotData();

        if (request()->query->has('SIRET')) {
            $this->application->company_siret = (string) request()->query->get('SIRET');
            $this->updated(self::SIRET_FIELD);
        }
    }

    /**
     * @return array<string, mixed>
     */
    protected function rules(): array
    {
        return \call_user_func_array('array_merge', $this->rulesByStep());
    }

    public function updated(string $propertyName): void
    {
        $this->validateOnly($propertyName);

        if ($propertyName === 'wage' || $propertyName === 'minimalContribution') {
            $this->updateContribution();
        }

        if ($this->noSiret === false && $propertyName === self::SIRET_FIELD) {
            $this->updateCompanyWithSiret();
        }
    }

    public function next(): void
    {
        $this->validate($this->rulesByStep()[$this->step]);

        if ($this->step === 2) {
            $this->updateSepaPrefill();
        }

        ++$this->step;
    }

    public function back(): void
    {
        --$this->step;
    }

    /**
     * @throws \Exception
     */
    public function submit(): void
    {
        $this->protectAgainstSpam();
        $this->validate();

        if ($this->triedLessThanAMinuteAgo('send-application:'.request()->getClientIp())) {
            return;
        }

        if (!$this->application->save()) {
            $this->addError('submit', __('validation.server_error'));
            Log::error('validation.server_error');

            return;
        }

        Log::info("Application {$this->application->id} submitted.");
        $this->redirect(route('success'));
    }

    #[On('updateSignature')]
    public function setSignature(string $signature_base64 = ''): void
    {
        $this->application->signature = $signature_base64;
        $this->updated('application.signature');
    }

    public function incrementContribution(): void
    {
        $this->application->contribution = floor($this->application->contribution) + 1;
    }

    /**
     * @return array<int<1, 4>, array<string, array<mixed>>>
     */
    private function rulesByStep(): array
    {
        return
            [
                1 => [
                    'application.name' => self::getTextValidators(true),
                    'application.firstname' => self::getTextValidators(true),
                    'application.address' => self::getTextValidators(true),
                    'application.postcode' => ['required', 'numeric', 'integer'],
                    'application.city' => self::getTextValidators(true),
                    'application.email' => self::getTextValidators(true, ['email']),
                    'application.mobile' => self::getTextValidators(true),
                    'application.birth_year' => ['nullable', 'numeric', 'min:1900', 'max:'.date('Y')],
                    'application.gender' => self::getTextValidators(false),
                ],
                2 => [
                    'application.company_name' => self::getTextValidators(false),
                    self::SIRET_FIELD => ['nullable', 'digits:14'],
                    'application.company_legal_address' => self::getTextValidators(false),
                    'application.company_work_address' => self::getTextValidators(false),
                ],
                3 => [
                    'wage' => ['nullable', 'numeric', 'min:0'],
                    'application.contribution' => ['required', 'numeric', 'min:1'],
                    'application.contribution_way' => ['required', new Enum(ContributionWay::class)],
                    'application.sepa_full_name' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_address' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_postcode' => [self::REQUIRED_IF_SEPA, 'nullable', 'numeric', 'integer'],
                    'application.sepa_city' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_country' => [self::REQUIRED_IF_SEPA, 'nullable', 'in:France'],
                    'application.iban' => [self::REQUIRED_IF_SEPA, 'nullable', new Iban()],
                    'application.bic' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA, 'nullable', 'alpha_num']),
                    'application.made_at' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.signature' => [self::REQUIRED_IF_SEPA, 'nullable', 'nullable', 'min:64'],
                ],
                4 => [
                    'application.mail_local' => ['nullable', 'boolean'],
                    'application.applicant_comment' => ['nullable', 'max:500'],

                    'terms' => ['accepted'],
                ],
            ];
    }

    private function updateContribution(): void
    {
        if ($this->minimalContribution) {
            $this->contributionPercentage = 0;
            $this->application->contribution = 1;

            return;
        }

        $this->contributionPercentage = $this->wage <= 1600 ? 0.5 : 0.65;
        $this->application->contribution = max(round((float) $this->wage * ($this->contributionPercentage / 100), 2), 1);
    }

    private function updateCompanyWithSiret(): void
    {
        try {
            $workplace = $this->sireneAPI->getWorkplace((string) $this->application->company_siret);
        } catch (AccessTokenException $exception) {
            Log::warning($exception->getMessage());
            $this->addErrorToSiretField();

            return;
        } catch (BadParameter $exception) {
            Log::debug($exception->getMessage());
            $this->addErrorToSiretField($exception->getMessage());

            return;
        } catch (CurlException $exception) {
            Log::notice($exception->getMessage());
            $this->addErrorToSiretField($exception->getCode() === 404 ? (string) __('form.siret.404') : null);

            return;
        }

        $this->application->company_name = $workplace->uniteLegale->denominationUniteLegale;
        $this->application->company_work_address = $workplace->adresse->__toString();

        try {
            $headOffice = $this->sireneAPI->getHeadOffice($workplace);
            $this->application->company_legal_address = $headOffice->adresse->__toString();
        } catch (\Throwable $exception) {
            Log::notice($exception->getMessage());
        }
    }

    private function addErrorToSiretField(?string $message = null): void
    {
        $this->validateOnly(
            self::SIRET_FIELD,
            [self::SIRET_FIELD => fn (string $attr, mixed $val, \Closure $fail) => $fail($message ?? __('form.siret.generic'))]
        );
    }

    private function updateSepaPrefill(): void
    {
        $this->application->sepa_full_name = $this->application->name.' '.$this->application->firstname;
        $this->application->sepa_address = $this->application->address;
        $this->application->sepa_postcode = $this->application->postcode;
        $this->application->sepa_city = $this->application->city;
        $this->application->sepa_country = 'France';
    }
}

app/Livewire/ApplicationOverview.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\Application;
use Livewire\Component;

class ApplicationOverview extends Component
{
    public Application $application;
    public bool $showRestrictedInformation;
}

app/Livewire/SignatureInput.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Livewire\Attributes\Validate;
use Livewire\Component;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Livewire\WithFileUploads;

class SignatureInput extends Component
{
    use WithFileUploads;

    #[Validate('image|mimes:png,jpg|max:200')]
    public ?TemporaryUploadedFile $signatureFile = null;

    public function updated(string $propertyName): void
    {
        if ($propertyName === 'signatureFile' && $this->signatureFile instanceof TemporaryUploadedFile) {
            $this->dispatch(
                'updateSignature',
                "data:{$this->signatureFile->getMimeType()};base64,".base64_encode((string) $this->signatureFile->get())
            );
        }
    }
}

resources/views/application/application-steps/3-contribution.blade.php
<div class="form__section">
    <h2 class="form__section__instruction">
        Votre cotisation mensuelle dépend de votre rémunération nette. Elle permet de financer l'activité du syndicat.
    </h2>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label">
                <input wire:model.live="minimalContribution" name="employee" class="mr-2 leading-tight" type="checkbox">
                <span>Je demande la cotisation minimale de 1€ par mois</span>
            </label>
            <p>
                La cotisation minimale est prévu dans nos status, pour les adhérent∙es en grande difficulté financière.
            </p>
        </div>
    </div>

        @if(!$minimalContribution)
            <div class="form__input-group">
                <div class="form__input-group__element">
                    <label class="form__input-group__element__label" for="wage">
                        {{ __('validation.attributes.wage') }}
                    </label>
                    <div class="relative">
                        <input
                            wire:model.blur="wage"
                            name="wage"
                            id="wage"
                            type="number"
                            min=O
                            step=1
                            autocomplete="transaction-amount"
                            class="form__input-group__element__input"
                        >
                        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-12">
                            <span class="text-gray-800 sm:text-sm">€</span>
                        </div>
                    </div>

                    <p class="form__input-group__element__instruction">
                        Nous n'enregistrons pas votre salaire, il sert uniquement à calculer votre taux de cotisation.
                    </p>

                    @error('wage') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
                </div>
            </div>
        @endif

    <div class="form__input-group">
        <div class="form__input-group__element form__input-group__element_1/2">
            <p class="form__input-group__element__label" >
                Taux de cotisation
            </p>
            <p class="form__input-group__element__p">{{ $this->contributionPercentage }} %</p>
        </div>

        <div class="form__input-group__element form__input-group__element_1/2">
            <p class="form__input-group__element__label" >
                {{ __('validation.attributes.contribution') }}
            </p>
            <p class="form__input-group__element__p flex justify-between">{{ $application->contribution }} <button wire:click.prevent="incrementContribution">+</button></p>
            <p class="form__input-group__element__instruction">
                Si vous le souhaitez, vous pouvez indiquer une cotisation plus importante (avec le bouton <button wire:click.prevent="incrementContribution">+</button>).
            </p>
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label" for="contribution_way">
                {{ __('validation.attributes.contribution_way') }}
            </label>
            <select
                wire:model.live="application.contribution_way"
                name="contribution_way"
                id="contribution_way"
                required
                class="form__input-group__element__input"
            >
                @foreach(\App\Enums\ContributionWay::cases() as $contributionWay)
                    <option value="{{ $contributionWay }}" >
                        {{ __("form.contribution_way_value.$contributionWay->value") }}
                    </option>
                @endforeach
            </select>
            <p class="form__input-group__element__instruction @if($application->contribution_way !== \App\Enums\ContributionWay::SEPA) text-red-800 font-bold @endif">
                Pour de multiples raisons logistiques, nous préférons les règlements par prélèvements automatiques.
            </p>
            @if($application->contribution_way === \App\Enums\ContributionWay::CHECK)
                <p class="form__input-group__element__instruction text-red-800 font-bold">
                    Si vous ne réglez pas votre cotisation par prélèvements automatiques, préférez les virements aux chèques.
                </p>
            @endif
            @error('application.contribution_way') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>
</div>

@if($application->contribution_way === \App\Enums\ContributionWay::SEPA)
    <div class="form__section">
    <h2 class="form__section__instruction">Mandat de prélèvement SEPA</h2>

    <p>
        En signant ce formulaire de mandat, vous autorisez le Créancier à envoyer des instructions à votre banque pour débiter votre compte, et votre banque à
        débiter votre compte conformément aux instructions du Créancier.
        Vous bénéficiez du droit d’être remboursé par votre banque selon les conditions décrites dans la convention que vous avez passé avec elle.
        Une demande de remboursement doit être présentée dans les 8 semaines suivant la date de débit de votre compte pour un prélèvement autorisé.
    </p>

    <div class="my-4">
        <h3 class="font-bold">Créancier :</h3>
        <p>
            Syndicat Solidaires Informatique, 31 rue de la Grange Aux Belles 75001 Paris France.
        <p>
            Identifiant Créancier SEPA (ICS) : FR 23 ZZZ 458309
        </p>
    </div>

    <h3 class="font-bold">Débiteur :</h3>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label" for="full_name">
                {{ __('validation.attributes.full_name') }}
            </label>
            <input
                wire:model.blur="application.sepa_full_name"
                id="full_name"
                name="full_name"
                type="text"
                autocomplete="name"
                required
                class="form__input-group__element__input @error('application.sepa_full_name') errored @enderror"
            >
            @error('application.sepa_full_name') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label" for="address">
                {{ __('validation.attributes.address') }}
            </label>
            <input
                wire:model.blur="application.sepa_address"
                name="address"
                type="text"
                id="address"
                required
                autocomplete="street-address"
                class="form__input-group__element__input @error('application.sepa_address') errored @enderror"
            >
            @error('application.sepa_address') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element form__input-group__element_1/2">
            <label class="form__input-group__element__label" for="postcode">
                {{ __('validation.attributes.postcode') }}
            </label>
            <input
                wire:model.blur="application.sepa_postcode"
                name="postcode"
                type="text"
                id="postcode"
                required
                autocomplete="postal-code"
                class="form__input-group__element__input @error('application.sepa_postcode') errored @enderror"
            >
            @error('application.sepa_postcode') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>

        <div class="form__input-group__element form__input-group__element_1/2">
            <label class="form__input-group__element__label" for="city">
                {{ __('validation.attributes.city') }}
            </label>
            <input
                wire:model.blur="application.sepa_city"
                name="city"
                type="text"
                id="city"
                required
                autocomplete="city"
                class="form__input-group__element__input @error('application.sepa_city') errored @enderror"
            >
            @error('application.sepa_city') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <p class="form__input-group__element__label" >
                {{ __('validation.attributes.country') }}
            </p>
            <p class="form__input-group__element__p">France</p>
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label" for="iban">
                {{ __('validation.attributes.iban') }}
            </label>
            <input
                wire:model.blur="application.iban"
                name="iban"
                type="text"
                id="iban"
                required
                class="form__input-group__element__input @error('application.iban') errored @enderror"
            >
            @error('application.iban') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element">
            <label class="form__input-group__element__label" for="bic">
                {{ __('validation.attributes.bic') }}
            </label>
            <input
                wire:model.blur="application.bic"
                name="bic"
                type="text"
                id="bic"
                required
                class="form__input-group__element__input @error('application.bic') errored @enderror"
            >
            @error('application.bic') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>
    </div>

    <div class="form__input-group">
        <div class="form__input-group__element form__input-group__element_1/2">
            <label class="form__input-group__element__label" for="made_at">
                {{ __('validation.attributes.made_at') }}
            </label>
            <input
                wire:model.blur="application.made_at"
                name="made_at"
                type="text"
                id="made_at"
                required
                autocomplete="city"
                class="form__input-group__element__input @error('application.made_at') errored @enderror"
            >
            @error('application.made_at') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
        </div>

        <div class="form__input-group__element form__input-group__element_1/2">
            <p class="form__input-group__element__label" >
                {{ __('form.current_date') }}
            </p>
            <p class="form__input-group__element__p">{{ now()->format('d/m/Y') }}</p>
        </div>
    </div>

    <livewire:signature-input />
    @error('application.signature') <p class="form__input-group__element__error">{{ $message }}</p> @enderror

    <p>
        Note : Vos droits concernant le prélèvement sont expliqués dans un document que vous pouvez obtenir auprès de votre banque.
    </p>
    <p>
        Les informations contenues dans le présent mandat, qui doit être complété, sont destinées à n’être utilisées par le créancier que pour la gestion de sa
        relation avec son client. Elles pourront donner lieu à l’exercice, par ce dernier, de ses droits d’oppositions, d’accès et de rectification tels que prévus aux
        articles 38 et suivants dela loi n° 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés.
    </p>
    <p>
        Votre référence unique de mandat (RUM) vous sera transmise, avec votre carte d'adhérent-e. Celle-ci vous sera
        envoyée une fois par an ; elle accompagnera le justificatif de paiement de cotisations.
        Pour toute information, vous pouvez nous joindre par mail.
    </p>
</div>
@endif

resources/views/application/application-steps/nav.blade.php
<nav class="my-4" aria-label="étapes du formulaire">
    <ul class="sm:grid gap-10 lg:grid-cols-4 sm:grid-cols-2">
        <li class="flex items-center justify-between h-full">
            <p class="text-lg sm:text-2xl @if($step === 1) font-bold @endif" aria-current="{{ $step === 1 ? 'step' : 'false' }}">
                <span class="sm:hidden">1)</span> Informations personnelles
            </p>
            @include('application.application-steps.arrow')
        </li>
        <li class="flex items-center justify-between h-full">
            <p class="text-lg sm:text-2xl @if($step === 2) font-bold @endif" aria-current="{{ $step === 2 ? 'step' : 'false' }}">
                <span class="sm:hidden">2)</span> Situation professionnelle
            </p>
            @include('application.application-steps.arrow')
        </li>
        <li class="flex items-center justify-between h-full">
            <p class="text-lg sm:text-2xl @if($step === 3) font-bold @endif" aria-current="{{ $step === 3 ? 'step' : 'false' }}">
                <span class="sm:hidden">3)</span> Cotisation
            </p>
            @include('application.application-steps.arrow')
        </li>
        <li class="flex items-center justify-between h-full">
            <p class="text-lg sm:text-2xl @if($step === 4) font-bold @endif" aria-current="{{ $step === 4 ? 'step' : 'false' }}">
                <span class="sm:hidden">4)</span> Finalisation
            </p>
        </li>
    </ul>
</nav>