routes/web.php
<?php

declare(strict_types=1);

use App\Enums\Role;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PasswordResetLinkController;
use App\Livewire\UserForm;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static fn () => view('application.create'));
Route::get('/bulletin-adhesion-pdf', static fn () => redirect('/BulletinAdhesion.pdf'));
Route::get('/success', static fn () => view('application.success'))->name('success');

Route::get('/archives', static fn () => view('application.archives'))
    ->name('archives')
    ->middleware(['auth', 'role:'.Role::BOARD->value]);

Route::prefix('admin')
    ->middleware(['auth', 'role:'.Role::ADMIN->value, config('jetstream.auth_session'), 'verified'])
    ->group(static function (): void {
        Route::get('', static fn () => view('admin.index', ['ref' => base_path().'/.git/refs/heads/main']))->name('admin.index');

        Route::prefix('logs')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewLogs'])->name('admin.logs');
            Route::get('clear', [AdminController::class, 'clearLogs'])->name('admin.logs.clear');
        });

        Route::prefix('users')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewUsers'])->name(AdminController::ROUTE_NAMES['users']['index']);
            Route::get('/edit/{user}', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['edit']);
            Route::get('/create', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['create']);
        });

//        Route::get('/settings', SettingsForm::class)->name('admin.settings');
    });

Route::prefix('dashboard')
    ->middleware(['auth', 'role:'.Role::BOARD->value, config('jetstream.auth_session'), 'verified'])
    ->group(function (): void {
        Route::get('', \App\Livewire\Dashboard\Dashboard::class)
            ->name('dashboard.index')
            ->middleware(['auth', 'role:'.Role::BOARD->value]);

        Route::prefix('application')->group(function (): void {
            Route::get(
                'complete/{application}',
                \App\Livewire\ApplicationComplete::class
            )->name('dashboard.application.complete')
                ->middleware(['auth', 'role:'.Role::TREASURY->value]);
        });
});

if (Features::enabled(Features::resetPasswords())) {
    // Overwrite the forgot-password post route to add enumeration protections
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
        ->middleware(['guest:'.config('fortify.guard')])
        ->name('password.email');
}

app/Livewire/ApplicationComplete.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Enums\ApplicationStatus;
use App\Models\Application;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\Log;
use Livewire\Component;

class ApplicationComplete extends Component
{
    use HasTextFields;

    public Application $application;

    /**
     * @throws AuthorizationException
     */
    public function complete(): void
    {
        $this->validate();

        $this->authorize('complete', Application::class);
        $this->application->status = ApplicationStatus::COMPLETED;
        $this->application->update();
        Log::notice("Application {$this->application->id} completed. RUM: {$this->application->RUM}");

        redirect(route('dashboard.index'));
    }

    /**
     * @return array<string, array<string>>
     */
    public function rules(): array
    {
        return [
            'application.RUM' => self::getTextValidators(false, [ApplicationForm::REQUIRED_IF_SEPA]),
            'application.first_withdrawal_date' => [ApplicationForm::REQUIRED_IF_SEPA, 'nullable', 'date', 'after_or_equal:tomorrow'],
        ];
    }
}

app/Livewire/ApplicationForm.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Enums\ContributionWay;
use App\Models\Application;
use App\Rules\Iban;
use App\Services\SireneAPI;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rules\Enum;
use Livewire\Attributes\On;
use SolidairesInformatique\AccessTokenException;
use SolidairesInformatique\BadParameter;
use SolidairesInformatique\CurlException;
use Spatie\Honeypot\Http\Livewire\Concerns\HoneypotData;
use Spatie\Honeypot\Http\Livewire\Concerns\UsesSpamProtection;

class ApplicationForm extends RateLimitedComponent
{
    use ConvertEmptyStringsToNull;
    use HasTextFields;
    use UsesSpamProtection;

    public Application $application;
    public bool $employee = true;
    public bool $minimalContribution = false;
    public string $wage = '';
    public float $contributionPercentage = 0.5;
    public bool $terms = false;
    public int $step = 1;
    public bool $noSiret = false;
    private SireneAPI $sireneAPI;
    public HoneypotData $extraFields;

    private const SIRET_FIELD = 'application.company_siret';
    public const REQUIRED_IF_SEPA = 'required_if:application.contribution_way,'.ContributionWay::SEPA->value;

    public function boot(SireneAPI $sireneAPI): void
    {
        $this->sireneAPI = $sireneAPI;
    }

    public function mount(): void
    {
        $this->extraFields = new HoneypotData();

        if (request()->query->has('SIRET')) {
            $this->application->company_siret = (string) request()->query->get('SIRET');
            $this->updated(self::SIRET_FIELD);
        }
    }

    /**
     * @return array<string, mixed>
     */
    protected function rules(): array
    {
        return \call_user_func_array('array_merge', $this->rulesByStep());
    }

    public function updated(string $propertyName): void
    {
        $this->validateOnly($propertyName);

        if ($propertyName === 'wage' || $propertyName === 'minimalContribution') {
            $this->updateContribution();
        }

        if ($this->noSiret === false && $propertyName === self::SIRET_FIELD) {
            $this->updateCompanyWithSiret();
        }
    }

    public function next(): void
    {
        $this->validate($this->rulesByStep()[$this->step]);

        if ($this->step === 2) {
            $this->updateSepaPrefill();
        }

        ++$this->step;
    }

    public function back(): void
    {
        --$this->step;
    }

    /**
     * @throws \Exception
     */
    public function submit(): void
    {
        $this->protectAgainstSpam();
        $this->validate();

        if ($this->triedLessThanAMinuteAgo('send-application:'.request()->getClientIp())) {
            return;
        }

        if (!$this->application->save()) {
            $this->addError('submit', __('validation.server_error'));
            Log::error('validation.server_error');

            return;
        }

        Log::info("Application {$this->application->id} submitted.");
        $this->redirect(route('success'));
    }

    #[On('updateSignature')]
    public function setSignature(string $signature_base64 = ''): void
    {
        $this->application->signature = $signature_base64;
        $this->updated('application.signature');
    }

    public function incrementContribution(): void
    {
        $this->application->contribution = floor($this->application->contribution) + 1;
    }

    /**
     * @return array<int<1, 4>, array<string, array<mixed>>>
     */
    private function rulesByStep(): array
    {
        return
            [
                1 => [
                    'application.name' => self::getTextValidators(true),
                    'application.firstname' => self::getTextValidators(true),
                    'application.address' => self::getTextValidators(true),
                    'application.postcode' => ['required', 'numeric', 'integer'],
                    'application.city' => self::getTextValidators(true),
                    'application.email' => self::getTextValidators(true, ['email']),
                    'application.mobile' => self::getTextValidators(true),
                    'application.birth_year' => ['nullable', 'numeric', 'min:1900', 'max:'.date('Y')],
                    'application.gender' => self::getTextValidators(false),
                ],
                2 => [
                    'application.company_name' => self::getTextValidators(false),
                    self::SIRET_FIELD => ['nullable', 'digits:14'],
                    'application.company_legal_address' => self::getTextValidators(false),
                    'application.company_work_address' => self::getTextValidators(false),
                ],
                3 => [
                    'wage' => ['nullable', 'numeric', 'min:0'],
                    'application.contribution' => ['required', 'numeric', 'min:1'],
                    'application.contribution_way' => ['required', new Enum(ContributionWay::class)],
                    'application.sepa_full_name' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_address' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_postcode' => [self::REQUIRED_IF_SEPA, 'nullable', 'numeric', 'integer'],
                    'application.sepa_city' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.sepa_country' => [self::REQUIRED_IF_SEPA, 'nullable', 'in:France'],
                    'application.iban' => [self::REQUIRED_IF_SEPA, 'nullable', new Iban()],
                    'application.bic' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA, 'nullable', 'alpha_num']),
                    'application.made_at' => self::getTextValidators(false, [self::REQUIRED_IF_SEPA]),
                    'application.signature' => [self::REQUIRED_IF_SEPA, 'nullable', 'nullable', 'min:64'],
                ],
                4 => [
                    'application.mail_local' => ['nullable', 'boolean'],
                    'application.applicant_comment' => ['nullable', 'max:500'],

                    'terms' => ['accepted'],
                ],
            ];
    }

    private function updateContribution(): void
    {
        if ($this->minimalContribution) {
            $this->contributionPercentage = 0;
            $this->application->contribution = 1;

            return;
        }

        $this->contributionPercentage = $this->wage <= 1600 ? 0.5 : 0.65;
        $this->application->contribution = max(round((float) $this->wage * ($this->contributionPercentage / 100), 2), 1);
    }

    private function updateCompanyWithSiret(): void
    {
        try {
            $workplace = $this->sireneAPI->getWorkplace((string) $this->application->company_siret);
        } catch (AccessTokenException $exception) {
            Log::warning($exception->getMessage());
            $this->addErrorToSiretField();

            return;
        } catch (BadParameter $exception) {
            Log::debug($exception->getMessage());
            $this->addErrorToSiretField($exception->getMessage());

            return;
        } catch (CurlException $exception) {
            Log::notice($exception->getMessage());
            $this->addErrorToSiretField($exception->getCode() === 404 ? (string) __('form.siret.404') : null);

            return;
        }

        $this->application->company_name = $workplace->uniteLegale->denominationUniteLegale;
        $this->application->company_work_address = $workplace->adresse->__toString();

        try {
            $headOffice = $this->sireneAPI->getHeadOffice($workplace);
            $this->application->company_legal_address = $headOffice->adresse->__toString();
        } catch (\Throwable $exception) {
            Log::notice($exception->getMessage());
        }
    }

    private function addErrorToSiretField(?string $message = null): void
    {
        $this->validateOnly(
            self::SIRET_FIELD,
            [self::SIRET_FIELD => fn (string $attr, mixed $val, \Closure $fail) => $fail($message ?? __('form.siret.generic'))]
        );
    }

    private function updateSepaPrefill(): void
    {
        $this->application->sepa_full_name = $this->application->name.' '.$this->application->firstname;
        $this->application->sepa_address = $this->application->address;
        $this->application->sepa_postcode = $this->application->postcode;
        $this->application->sepa_city = $this->application->city;
        $this->application->sepa_country = 'France';
    }
}

app/Livewire/ApplicationOverview.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\Application;
use Livewire\Component;

class ApplicationOverview extends Component
{
    public Application $application;
    public bool $showRestrictedInformation;
}

app/Livewire/ConvertEmptyStringsToNull.php
<?php

declare(strict_types=1);

namespace App\Livewire;

/**
 * @source https://github.com/livewire/livewire/issues/823#issuecomment-821074805
 */
trait ConvertEmptyStringsToNull
{
    /**
     * @var string[]
     */
    protected array $convertEmptyStringsExcept = [];

    public function updatedConvertEmptyStringsToNull(string $name, mixed $value): void
    {
        if (!\is_string($value) || \in_array($name, $this->convertEmptyStringsExcept, true)) {
            return;
        }

        $value = trim($value);
        $value = $value === '' ? null : $value;

        data_set($this, $name, $value);
    }
}

app/Livewire/Dashboard/Dashboard.php
<?php

declare(strict_types=1);

namespace App\Livewire\Dashboard;

use Livewire\Attributes\Title;
use Livewire\Attributes\Url;
use Livewire\Component;

#[Title("Gestion des demands d'adhésions")]
class Dashboard extends Component
{
    #[Url]
    public string $filter = '';
}

app/Livewire/Dashboard/ToDo.php
<?php

declare(strict_types=1);

namespace App\Livewire\Dashboard;

use App\Enums\ApplicationStatus;
use App\Models\Application;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Component;

class ToDo extends Component
{
    /** @var ApplicationStatus[] */
    private const array STATUSES = [
        ApplicationStatus::NEW,
        ApplicationStatus::VALIDATED,
        ApplicationStatus::COMPLETED,
        ApplicationStatus::READY,
    ];

    /** @var array<string, int> */
    public array $counts;

    #[Url]
    public string $filter = '';

    /** @var string[] */
    public array $notifications = [];

    private User $user;

    public function __construct()
    {
        $user = Auth::user();
        if (!$user instanceof User) {
            throw new \RuntimeException("Couldn't find user.");
        }
        $this->user = $user;
    }

    public function mount(): void
    {
        foreach (self::STATUSES as $status) {
            $notification = $status->notificationOption();
            if ($notification === null || $this->user->option($notification)->value !== '1') {
                continue;
            }
            $this->notifications[] = $status->value;
        }

        $this->updateCounts();
    }

    public function updatedNotifications(): void
    {
        foreach (self::STATUSES as $status) {
            $notification = $status->notificationOption();
            if ($notification === null) {
                Log::warning("Can't update notification for status {$status->name}.");

                continue;
            }
            $this->user->option($notification)->setBool(
                \in_array($status->value, $this->notifications, true)
            );
        }
    }

    #[On('move-application')]
    public function updateCounts(): void
    {
        foreach (self::STATUSES as $status) {
            $this->counts[$status->value] = Application::query()->where('status', $status)->count();
        }
    }
}

app/Livewire/FlashMessage.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Livewire\Component;

class FlashMessage extends Component
{
    public string $message;
}

app/Livewire/HasTextFields.php
<?php

declare(strict_types=1);

namespace App\Livewire;

trait HasTextFields
{
    /**
     * @param array<int, string> $rules
     *
     * @return array<int, string>
     */
    public static function getTextValidators(bool $required, array $rules = []): array
    {
        return [$required ? 'required' : 'nullable', 'string', 'max:255', ...$rules];
    }
}

app/Livewire/RateLimitedComponent.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Illuminate\Support\Facades\RateLimiter;
use Livewire\Component;

abstract class RateLimitedComponent extends Component
{
    final protected function triedLessThanAMinuteAgo(string $rateLimiterKey): bool
    {
        if (!auth()->guest()) {
            return false;
        }

        if (RateLimiter::tooManyAttempts($rateLimiterKey, 1)) {
            $seconds = RateLimiter::availableIn($rateLimiterKey);
            $this->addError('submit', __('validation.throttled_with_seconds', ['seconds' => $seconds]));

            return true;
        }

        RateLimiter::hit($rateLimiterKey);

        return false;
    }
}

app/Livewire/ShowUsers.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Livewire\Component;

class ShowUsers extends Component
{
    /**
     * @var Collection<int, User>
     */
    public Collection $users;

    public function mount(): void
    {
        $this->users = User::all();
    }
}

resources/views/livewire/application-complete.blade.php
<div>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Finaliser l'adhésion
        </h2>
        <p>
            La finalisation de l'adhésion entraîne l'ajout de la personne dans la base d'adhérent·es et notifie le bureau ainsi que le
            groupe d'accueil.
        </p>
    </x-slot>

    <div class="form__section">
        <p class="form__section__instruction">
            {{ $application->firstname }} {{ $application->name }}
            <span title="{{ $application->id }}" class="font-mono text-xs">{{ $application->getShortenedId() }}</span>
        </p>

        @if($application->contribution_way === \App\Enums\ContributionWay::SEPA)
            <p class="my-2">
                Ces informations seront envoyées dans le mail de bienvenue.
            </p>

            <div class="form__input-group">
                <div class="form__input-group__element form__input-group__element_1/2">
                    <label class="form__input-group__element__label" for="RUM">
                        Référence unique de mandat (RUM)
                    </label>
                    <input
                        wire:model.blur="application.RUM"
                        id="RUM"
                        type="text"
                        required
                        autofocus
                        class="form__input-group__element__input @error('application.RUM') errored @enderror"
                    >
                    @error('application.RUM') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
                </div>
                <div class="form__input-group__element form__input-group__element_1/2">
                    <label class="form__input-group__element__label" for="first_withdrawal_date">
                        Date du premier prélèvement
                    </label>
                    <input
                        wire:model.blur="application.first_withdrawal_date"
                        id="first_withdrawal_date"
                        type="date"
                        required
                        autofocus
                        min="{{\Carbon\Carbon::now()->format('Y-m-d')}}"
                        max="{{\Carbon\Carbon::now()->addMonths(2)->format('Y-m-d')}}"
                        class="form__input-group__element__input @error('application.first_withdrawal_date') errored @enderror"
                    >
                    @error('application.first_withdrawal_date') <p class="form__input-group__element__error">{{ $message }}</p> @enderror

                </div>
            </div>
        @endif

        <p class="my-2">
            L'ajout des données dans le CRM n'est pas encore automatisé, il faut le faire manuellement à cette étape.
        </p>

        <input
            wire:loading.attr="disabled"
            wire:click.prevent="complete"
            type="submit"
            class="form__submit @error('submit') form__submit_error @enderror"
            value="{{ __('dashboard.actions.complete') }}"
        >

        <p wire:loading class="inline">
            Sauvegarde en cours…
        </p>

        <p class="my-2">
            Cette étape archive automatiquement le bulletin d'adhésion
            @if($application->contribution_way === \App\Enums\ContributionWay::SEPA) et le mandat SEPA @endif
            en PDF sur le cloud.
        </p>

        <livewire:application-overview :application="$application" :showRestrictedInformation="true" />
    </div>
</div>

resources/views/livewire/application-form.blade.php
<form wire:submit="submit" class="form">
    @csrf
    <x-honeypot livewire-model="extraFields" />

    @include('application.application-steps.nav')

    @switch($step)
        @case(1)
            @include('application.application-steps.1-personal-data')
            @break
        @case(2)
            @include('application.application-steps.2-company')
            @break
        @case(3)
            @include('application.application-steps.3-contribution')
            @break
        @case(4)
            @include('application.application-steps.4-finalization')
            @break
    @endswitch

    @if($step > 1)
        <button
            wire:click.prevent="back"
            class="form__submit_white"
        >Retour</button>
    @endif
    @if($step === 4)
        <button type="submit" class="form__submit @error('submit') form__submit_error @enderror">
            <span>{{ __('form.send_application') }}</span>
        </button>
    @else
        <input
            wire:click.prevent="next"
            type="submit"
            class="form__submit @error('submit') form__submit_error @enderror"
            value="Suivant"
        >
    @endif
    @error('submit') <p class="form__input-group__element__error">{{ $message }}</p> @enderror

</form>

<script>
    document.addEventListener('livewire:init', () => {
        Livewire.hook('component.init', ({ component }) => {
            if (component.name === 'signature-input') {
                function debounce(func){
                    let timer;
                    return (...args) => {
                        clearTimeout(timer);
                        timer = setTimeout(() => { func.apply(this, args); }, 300);
                    };
                }
                const sendToLivewire = debounce(() => @this.dispatch('updateSignature', [canvas.toDataURL()]));

                const canvas = document.getElementById('signature-freehand');
                canvas.classList.remove('!hidden');

                const mouse = {x: 0, y: 0};
                const last_mouse = {x: 0, y: 0};
                canvas.addEventListener('mousemove', function(e) {
                    last_mouse.x = mouse.x;
                    last_mouse.y = mouse.y;
                    mouse.x = e.pageX - this.offsetLeft;
                    mouse.y = e.pageY - this.offsetTop;
                });

                let ctx = canvas.getContext('2d')
                const onPaint = () => {
                    ctx.beginPath();
                    ctx.moveTo(last_mouse.x, last_mouse.y);
                    ctx.lineTo(mouse.x, mouse.y);
                    ctx.closePath();
                    ctx.stroke();
                    sendToLivewire();
                };

                canvas.addEventListener('mousedown', () => canvas.addEventListener('mousemove', onPaint));
                canvas.addEventListener('mouseup', () => canvas.removeEventListener('mousemove', onPaint));

                {
                    const resetBtn = document.getElementById('reset-signature')
                    resetBtn.classList.remove('hidden');
                    resetBtn.addEventListener('click', () => {
                        ctx.clearRect(0, 0, canvas.width, canvas.height);
                        @this.dispatch('updateSignature');
                    })
                }
            }
        })
    })
</script>

resources/views/livewire/flash-message.blade.php
<div class="mx-auto max-w-xl border m-4 rounded" role="alert" aria-live="assertive" aria-atomic="true" data-mdb-autohide="false">
    <p class="bg-white px-4 py-5 sm:px-6 rounded">
        {{ $message }}
    </p>
</div>

resources/views/livewire/settings-form.blade.php
<div class="w-full max-w-4xl mx-auto mt-2">
{{--    Page non utilisée --}}
    <header class="mb-2 text-center">
        <h1 class="text-4xl">Paramètres</h1>
    </header>

    @if (session('error'))
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white px-4 py-5 sm:px-6 rounded">
                <p class="text-red-500">
                    {{ session('error') }}
                </p>
            </div>
        </div>
    @endif
    @if (session('error'))
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white px-4 py-5 sm:px-6 rounded">
                <p class="text-red-500">
                    {{ session('error') }}
                </p>
            </div>
        </div>
    @endif

    <div class="mt-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white px-4 py-5 sm:px-6 rounded">
                <form wire:submit="submit" method="POST" class="form">
                    @csrf

                    <div class="form__input-group">
                        <div class="form__input-group__element">
                            <label class="form__input-group__element__label" for="pseudo">
                                Mail du groupe d'accueil
                            </label>
                            <input
                                wire:model="welcome_group_mail.value"
                                type="email"
                                required
                                class="form__input-group__element__input @error('welcome_group_mail.value') errored @enderror"
                            >
                            @error('welcome_group_mail.value') <p class="form__input-group__element__error">{{ $message }}</p> @enderror
                        </div>
                    </div>

                    <button type="submit" class="form__submit @error('submit') form__submit_error @enderror">
                        <span>Mettre à jour</span>
                    </button>
                    @error('submit')
                    <p class="form__input-group__element__error">{{ $message }}</p>
                    @enderror
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/show-application.blade.php
<div class="overflow-hidden bg-white shadow border-2 mb-6 sm:rounded-lg">
    <div class="border-b mb-2 flex justify-between px-4 py-5 sm:px-6 align-middle">
        <div class="flex">
            <h3 class="m-auto text-lg leading-6 text-gray-900">
                {{ $application->firstname }} {{ $application->name }}
                <span title="{{ $application->id }}" class="font-mono text-xs">{{ $application->getShortenedId() }}</span>
            </h3>
        </div>
        <div class="flex items-baseline flex-wrap">
            <p class="mx-1">
                {{ __("dashboard.status.{$application->status->value}", ['timeDiff' => $application->updated_at->diffForHumans()]) }}
            </p>

            <div class="flex flex-wrap">
                @if($showDone)
                    <form wire:submit="done" class="mx-1">
                        <input class="form__submit w-full my-1 md:w-auto" type="submit" value="{{$doneName}}" />
                    </form>
                @endif
                @if($showReject)
                    {{-- TODO: confirmation with comment --}}
                    <form wire:submit="reject" class="mx-1">
                        <input class="form__submit form__submit_error w-full my-1 md:w-auto" type="submit" value="{{ __('dashboard.actions.reject') }}" />
                    </form>
                @endif
            </div>
        </div>
    </div>

    <livewire:application-overview :application="$application" :showRestrictedInformation="true" />
</div>

resources/views/livewire/show-applications.blade.php
<section>
    <p class="text-xl">
        {{ $title }}
    </p>
    <p>
        {{ $subtitle }}
    </p>

    <div class="max-w-7xl mx-auto sm:p-6 lg:p-8">
        @if($applications->count() === 0)
            <p>{{ __('dashboard.no_applications_found') }}</p>
        @endif

        @foreach ($applications as $application)
            <livewire:show-application :application="$application" wire:key="{{ $application->id }}" />
        @endforeach
    </div>
</section>

resources/views/livewire/signature-input.blade.php
<div class="form__input-group">
    <div class="form__input-group__element">
        @if($signatureFile === null)
            <label class="form__input-group__element__label" for="signature">
                Dessinez votre signature
            </label>
            <canvas
                id="signature-freehand"
                class="form__input-group__element__input border-black bg-white max-w-md !p-0 !hidden"
                style="height: 100px; width: 300px"
                width="300px"
                height="100px"
            >
                Votre navigateur ne supporte pas la technologie canvas, téléversez un scan de votre signature <label for="signature-file" class="cursor-pointer underline">en cliquant ici</label>.
            </canvas>
            <button id="reset-signature" class="form__submit_white my-2 hidden">Effacer</button>
        @endif

        <label>
            <span class="form__input-group__element__label">En cas d'impossibilité, téléversez votre signature</span> (PNG et JPG, maximum 200 kilo-octets)
            <input type="file" wire:model="signatureFile">
        </label>
    </div>
</div>