routes/web.php
<?php

declare(strict_types=1);

use App\Enums\Role;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PasswordResetLinkController;
use App\Livewire\UserForm;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static fn () => view('application.create'));
Route::get('/bulletin-adhesion-pdf', static fn () => redirect('/BulletinAdhesion.pdf'));
Route::get('/success', static fn () => view('application.success'))->name('success');

Route::get('/archives', static fn () => view('application.archives'))
    ->name('archives')
    ->middleware(['auth', 'role:'.Role::BOARD->value]);

Route::prefix('admin')
    ->middleware(['auth', 'role:'.Role::ADMIN->value, config('jetstream.auth_session'), 'verified'])
    ->group(static function (): void {
        Route::get('', static fn () => view('admin.index', ['ref' => base_path().'/.git/refs/heads/main']))->name('admin.index');

        Route::prefix('logs')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewLogs'])->name('admin.logs');
            Route::get('clear', [AdminController::class, 'clearLogs'])->name('admin.logs.clear');
        });

        Route::prefix('users')->group(static function (): void {
            Route::get('', [AdminController::class, 'viewUsers'])->name(AdminController::ROUTE_NAMES['users']['index']);
            Route::get('/edit/{user}', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['edit']);
            Route::get('/create', UserForm::class)->name(AdminController::ROUTE_NAMES['users']['create']);
        });

//        Route::get('/settings', SettingsForm::class)->name('admin.settings');
    });

Route::prefix('dashboard')
    ->middleware(['auth', 'role:'.Role::BOARD->value, config('jetstream.auth_session'), 'verified'])
    ->group(function (): void {
        Route::get('', \App\Livewire\Dashboard\Dashboard::class)
            ->name('dashboard.index')
            ->middleware(['auth', 'role:'.Role::BOARD->value]);

        Route::prefix('application')->group(function (): void {
            Route::get(
                'complete/{application}',
                \App\Livewire\ApplicationComplete::class
            )->name('dashboard.application.complete')
                ->middleware(['auth', 'role:'.Role::TREASURY->value]);
        });
});

if (Features::enabled(Features::resetPasswords())) {
    // Overwrite the forgot-password post route to add enumeration protections
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
        ->middleware(['guest:'.config('fortify.guard')])
        ->name('password.email');
}

app/Livewire/FlashMessage.php
<?php

declare(strict_types=1);

namespace App\Livewire;

use Livewire\Component;

class FlashMessage extends Component
{
    public string $message;
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title ?? config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    <!-- Styles -->
    @livewireStyles
</head>
<body class="font-sans antialiased">
<x-banner/>

<div class="min-h-screen bg-gray-100">
    @livewire('navigation-menu')

    <main class="p-6">
        @if(session('error_message'))
            <div class="max-w-4xl m-auto">
                <p class="bg-red-200 rounded p-4 text-center m-2">
                    {{ session('error_message') }}
                </p>
            </div>
        @endif
        @if(session('success_message'))
            <div class="max-w-4xl m-auto">
                <p class="bg-green-200 rounded p-4 text-center m-2">
                    {{ session('success_message') }}
                </p>
            </div>
        @endif
            {{ $slot }}
    </main>
</div>

@stack('modals')

@livewireScripts
</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <main class="font-sans antialiased">
            {{ $slot }}
        </main>
        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <header class="mt-2 mx-auto">
            <div class="flex justify-around">
                <h1>
                    <span class="text-4xl block">Adhérez en ligne</span>
                    <span class="text-2xl block">Ensemble, on est plus fort·es !</span>
                </h1>
                <img class="px-6 max-w-xs hidden md:block" src="/logo.svg" alt="Solidaires Informatique, Union syndicale Solidaires">
            </div>
            @if(\Illuminate\Support\Facades\Auth::guest())
                <div class="text-center text-lg text-red-700 my-12">
                    <p>
                        Ce site est en cours de développement, ne l'utilisez pas adhérer.
                    </p>
                    <p>
                        Pour adhérer, remplissez <a class="link" href="/bulletin-adhesion-pdf">le bulletin d'adhésion en PDF</a> et envoyez le nous par mail.
                    </p>
                </div>
            @endif
        </header>

        @if(session('success_message'))
            <livewire:flash-message :message="session('success_message')" />
        @endif

        <main class="font-sans antialiased mt-2">
            {{ $slot }}
        </main>

        <footer class="mt-6 py-6 mx-auto text-center bg-si-blue-dark text-white">
            <p>
                Le formulaire d'adhésion est aussi disponible au format PDF (à retourner par courrier ou par mail) : <a class="light-link" href="/bulletin-adhesion-pdf">bulletin d'adhésion en PDF</a>
            </p>

            <p>
                Si votre situation nécessite une aide d'urgence, contactez nous par mail :
                contact<span id="replace-arobase">[arobase]</span>solidairesinformatique<span id="replace-point">[point]</span>org
            </p>

            <p>
                <a class="light-link" href="https://solidairesinformatique.org">Retourner sur le site</a>
                 - <a href="https://gitlab.com/solidaires-informatique/adhesion" class="light-link">Voir le code source</a>
            </p>
        </footer>

        <noscript>
            <div class="absolute top-0 bg-si-blue-dark text-white text-xl w-full p-4 text-center">
                <p>Pour utiliser le formulaire d'adhésion en ligne, veuillez activer JavaScript.</p>
                <p>Sinon, vous pouvez utiliser le <a class="light-link" href="/bulletin-adhesion-pdf">bulletin en PDF</a>.</p>
            </div>
        </noscript>
        <script async defer>
            document.getElementById('replace-arobase').innerText = '@';
            document.getElementById('replace-point').innerText = '.';
        </script>
        @livewireScripts
    </body>
</html>